server:
  port: 8080
  servlet:
    context-path: /pet_care_identity

spring:
  application:
    name: identity_service
  datasource:
    url: "jdbc:mysql://localhost:3306/pet_care_identity?createDatabaseIfNotExist=true"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  signerKey: "cnGDY/xuGdmN0zD9ktlVWVA8/Vki3ep0ZiDNJC++DHFSIerOdQJNH4epcyEy+YZR"
  valid-duration: 3600 # in seconds
  refreshable-duration: 36000 # in seconds