server:
  port: 8082
  servlet:
    context-path: /pet_care_user

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

jwt:
  signerKey: ${JWT_SIGNER_KEY}

spring:
  application:
    name: user_service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/pet_care_user?createDatabaseIfNotExist=true}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.pet_care.user_service: DEBUG
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.apache.catalina: WARN
    org.apache.tomcat: WARN
  pattern:
    console: "%d{HH:mm:ss} [%highlight(%-5level)] [user_service] %cyan(%logger{36}) - %msg%n"
