version: '3.8'

services:
  # --- Database  ---
  mysql-db:
    image: mysql:8.0
    container_name: petcare-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - petcare-network

  # --- (RabbitMQ) ---
  rabbitmq:
    image: rabbitmq:3-management
    container_name: petcare-rabbitmq
    hostname: rabbit-server
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - petcare-network

networks:
  petcare-network:
    driver: bridge

volumes:
  mysql_data: